In [1]:
# to get the all subsets of a set for implement exhaustive feature selection
from itertools import chain, combinations

# to read and manipulation data
import pandas as pd

# to download data of the cryptocurrency
import yfinance as yf

# to preprocess the data, make, train and evaluate the model
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
import sklearn.metrics as metrics

In [39]:
# download data of the cryptocurrency

df_xmr = yf.download(tickers="XMR-USD", period="max", interval="1d", start="2023-01-01", end="2023-10-09")

[*********************100%%**********************]  1 of 1 completed


In [38]:
# show the downloaded data
df_xmr.head()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-01-01  147.309662  148.931030  146.437485  148.576935  148.576935   
2023-01-02  148.582184  149.623535  147.943558  147.943558  147.943558   
2023-01-03  147.933929  149.027832  147.628860  148.487930  148.487930   
2023-01-04  148.466995  152.488983  148.342621  150.743652  150.743652   
2023-01-05  150.790253  155.921738  150.769043  155.921738  155.921738   

              Volume  Price increase (in the next day)  
Date                                                    
2023-01-01  36453347                               NaN  
2023-01-02  47050925                               NaN  
2023-01-03  48662135                               1.0  
2023-01-04  83915181                               1.0  
2023-01-05  78049428                               0.0

In [40]:
actual_class = (
    (df_xmr.loc["2023-01-04":, "Close"].to_numpy() > df_xmr.loc["2023-01-03":"2023-10-07", "Close"]).astype(int)
)
df_xmr = df_xmr.drop("2023-10-08")
df_xmr["Price increase (in the next day)"] = actual_class

In [47]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# Split the data into training, validation, and test sets
train_data, test_data = train_test_split(df_xmr, test_size=0.2, shuffle=False)
train_data, val_data = train_test_split(train_data, test_size=0.2, shuffle=False)

# Define feature columns and target variable
feature_cols = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
target_col = 'Price increase (in the next day)'

# Split features and target variable for training, validation, and test sets
X_train, y_train = train_data[feature_cols], train_data[target_col]
X_val, y_val = val_data[feature_cols], val_data[target_col]
X_test, y_test = test_data[feature_cols], test_data[target_col]

# Handle missing values in the features and target variables
imputer = SimpleImputer(strategy="mean")
X_train = imputer.fit_transform(X_train)
X_val = imputer.transform(X_val)
X_test = imputer.transform(X_test)

# Handle missing values in the target variable
imputer_target = SimpleImputer(strategy="most_frequent")
y_train = imputer_target.fit_transform(y_train.values.reshape(-1, 1)).ravel()
y_val = imputer_target.transform(y_val.values.reshape(-1, 1)).ravel()
y_test = imputer_target.transform(y_test.values.reshape(-1, 1)).ravel()

# Train the random forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the validation set
val_predictions = model.predict(X_val)

# Evaluate model performance on the validation set
accuracy = accuracy_score(y_val, val_predictions)
precision = precision_score(y_val, val_predictions)
recall = recall_score(y_val, val_predictions)
f1 = f1_score(y_val, val_predictions)
auc = roc_auc_score(y_val, val_predictions)
confusion = confusion_matrix(y_val, val_predictions)

# Print evaluation metrics and confusion matrix
print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(f'AUC: {auc}')
print('Confusion Matrix:')
print(confusion)

# Make predictions on the test set
test_predictions = model.predict(X_test)

# Evaluate model performance on the test set
test_accuracy = accuracy_score(y_test, test_predictions)
test_precision = precision_score(y_test, test_predictions)
test_recall = recall_score(y_test, test_predictions)
test_f1 = f1_score(y_test, test_predictions)
test_auc = roc_auc_score(y_test, test_predictions)
test_confusion = confusion_matrix(y_test, test_predictions)

# Print evaluation metrics and confusion matrix for the test set
print('\nTest Set Performance:')
print(f'Test Accuracy: {test_accuracy}')
print(f'Test Precision: {test_precision}')
print(f'Test Recall: {test_recall}')
print(f'Test F1 Score: {test_f1}')
print(f'Test AUC: {test_auc}')
print('Test Confusion Matrix:')
print(test_confusion)

Accuracy: 0.5555555555555556
Precision: 0.5882352941176471
Recall: 0.43478260869565216
F1 Score: 0.5
AUC: 0.558300395256917
Confusion Matrix:
[[15  7]
 [13 10]]

Test Set Performance:
Test Accuracy: 0.625
Test Precision: 0.6304347826086957
Test Recall: 0.8787878787878788
Test F1 Score: 0.7341772151898734
Test AUC: 0.5698287220026351
Test Confusion Matrix:
[[ 6 17]
 [ 4 29]]


In [48]:
val_predictions

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1.])

In [49]:
# Evaluate model performance on the test set
test_accuracy = accuracy_score(y_test, test_predictions)
test_precision = precision_score(y_test, test_predictions)
test_recall = recall_score(y_test, test_predictions)
test_f1 = f1_score(y_test, test_predictions)
test_auc = roc_auc_score(y_test, test_probabilities)
test_confusion = confusion_matrix(y_test, test_predictions)

# Print evaluation metrics and confusion matrix for the test set
print('\nTest Set Performance:')
print(f'Test Accuracy: {test_accuracy}')
print(f'Test Precision: {test_precision}')
print(f'Test Recall: {test_recall}')
print(f'Test F1 Score: {test_f1}')
print(f'Test AUC: {test_auc}')
print('Test Confusion Matrix:')
print(test_confusion)


Test Set Performance:
Test Accuracy: 0.625
Test Precision: 0.6304347826086957
Test Recall: 0.8787878787878788
Test F1 Score: 0.7341772151898734
Test AUC: 0.5
Test Confusion Matrix:
[[ 6 17]
 [ 4 29]]
